apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ubuntu
  template:
    metadata:
      labels:
        name: ubuntu
    spec:
      hostname: ubuntu
      containers:
      - name: ubuntu18
        imagePullPolicy: Always
        image: ubuntu:16.04
        tty: true
