version: '3'
services:
  ffmpeg-forward:
    image: linuxserver/ffmpeg:version-4.4-cli
    container_name: ffmpeg-forward
    hostname: ffmpeg-forward
    entrypoint: ["/bin/bash", "-c"]
    command: ["ffmpeg -re -i rtmp://out.xtj99.com/live/720 
              -c:a aac -c:v h264 
              -f flv 
              rtmp://a326dace498d5484b8124cc360792d70-801149410.ap-northeast-1.elb.amazonaws.com/live/720"]
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
