## http://[WSE_IP_PARAM]:8088/enginemanager
version: '3'
services:
  wowza:
    image: wowzamedia/wowza-streaming-engine-linux:4.8.12
    container_name: wowza
    hostname: wowza
    entrypoint: ["/sbin/entrypoint.sh"]
    environment:
      WSE_MGR_USER: wowza
      WSE_MGR_PASS: wowza
      WSE_LIC: ""
      WSE_IP_PARAM: ""
    ports:
      - "1935:1935"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
    restart: always
    volumes:
      - ./logs:/usr/local/WowzaStreamingEngine/logs
      - ./conf:/usr/local/WowzaStreamingEngine-4.8.12+1/conf/live
      - ./wms-server.jar:/usr/local/WowzaStreamingEngine-4.8.12+1/lib/wms-server.jar
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

